"""Initial migration

Revision ID: aebb29489554
Revises: 
Create Date: 2023-12-28 16:19:25.891977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebb29489554'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status', 'log_entries', ['status'], unique=False)
    op.create_index('idx_timestamp', 'log_entries', ['timestamp'], unique=False)
    op.create_index('idx_timestamp_user_id', 'log_entries', ['timestamp', 'user_id'], unique=False)
    op.create_index('idx_user_id', 'log_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_log_entries_status'), 'log_entries', ['status'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_entries_user_id'), 'log_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_user_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_status'), table_name='log_entries')
    op.drop_index('idx_user_id', table_name='log_entries')
    op.drop_index('idx_timestamp_user_id', table_name='log_entries')
    op.drop_index('idx_timestamp', table_name='log_entries')
    op.drop_index('idx_status', table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
